[package]
name = "pbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
osmpbf = "0.3.0"
raqote = "0.8.2"
softbuffer = "0.2.0"
winit = "0.28.2"
